name: publish-beta-packages
env:
  ACTIONS_ALLOW_UNSECURE_COMMANDS: true
on: [push]
jobs:
  publish:
    timeout-minutes: 30
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup node
        uses: actions/setup-node@v2
        with:
          node-version: '16'

      - name: Install dependencies
        run: |
          git checkout .


      - name: Publish to NPM
        run: |
          npm config set '//registry.npmjs.org/:_authToken' "${{ secrets.NPM_TOKEN }}"
          node tools/update-beta-package-version.js
          # @see https://github.com/lerna/lerna/blob/main/commands/publish/README.md#--dist-tag-tag
          NODE_OPTIONS="--max_old_space_size=4096" lerna publish from-git --yes --dist-tag beta

      - name: Latest Blocklet Server CLI Version
        run: |
          npm info lerna-test-for-skypesky-copy
          npm info lerna-test-for-skypesky

     
