name: publish-beta-packages
env:
  ACTIONS_ALLOW_UNSECURE_COMMANDS: true
on:
  push:
    branches:
      - master
jobs:
  publish-beta-packages:
    timeout-minutes: 30
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup node
        uses: actions/setup-node@v2
        with:
          node-version: '16'

      - name: Install dependencies
        run: |
          lerna bootstrap
          git checkout .

      - name: Extract current version
        id: get_version
        run: |
          CURRENT_VERSION=$(cat version | awk '{$1=$1;print}')
          echo "CURRENT_VERSION=${CURRENT_VERSION}" >> $GITHUB_ENV

      - name: Config Git
        run: |
          git config --local user.name "bot"
          git config --local user.email "bot@arcblock.io"

      - name: Publish to NPM
        run: |
          npm config set '//registry.npmjs.org/:_authToken' "${{ secrets.NPM_TOKEN }}"
          # 获取最新的 commit hash
          LATEST_COMMIT_ID=$(git rev-parse --verify HEAD)
          # 截取前 8 位字符串
          COMMIT_HASH=${LATEST_COMMIT_ID:0:8}
          # 构建 beta 版本号
          BETA_VERSION="${CURRENT_VERSION}-beta-${COMMIT_HASH}"
          # 更新所有的版本号
          lerna version ${BETA_VERSION} --exact --no-push --force-publish --yes
          echo "publish version ${BETA_VERSION}"
          # @see https://github.com/lerna/lerna/blob/main/commands/publish/README.md#--dist-tag-tag
          NODE_OPTIONS="--max_old_space_size=4096" lerna publish from-git --yes --dist-tag beta
          
          
      - name: Latest Blocklet Server CLI Version
        run: |
          npm info lerna-test-for-skypesky-copy
          npm info lerna-test-for-skypesky

      # @see https://github.com/marketplace/actions/github-push
      # @see https://stackoverflow.com/a/58393457
      - name: 'Create Dev Branch'
        run: |
          git reset --hard $LATEST_COMMIT_ID
          git remote set-url origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}
          git checkout -b dev
          set +e && git push origin dev
          exit 0

     
