name: skip-ci
on:
  pull_request:
    types:
      - opened
      - edited
      - synchronize
    branches: 
      - master

jobs:
  cancel:

    print_title_of_pr:
      runs-on: ubuntu-20.04
      steps:
      - name : Print Title of PR
        run: echo The Title of your PR is ${{ github.event.pull_request.title }}

    name: auto-cancellation-running-action
    runs-on: ubuntu-latest
    if: "! contains(toJSON(github.event.commits.*.message), '[skip ci]')"
    steps:
      - uses: fauguste/auto-cancellation-running-action@0.1.4
        with:
          githubToken: ${{ secrets.GIT_HUB_TOKEN }}
