name: version-check-for-npm
env:
  ACTIONS_ALLOW_UNSECURE_COMMANDS: true

on:
  pull_request:
    branches:
      - master
      - release

jobs:
  skip-ci-when-include-wip:
    runs-on: ubuntu-latest
    steps:
      - name: WIP Blocker
        uses: rafaelbeckel/wip-blocker

  version-check-for-npm:
    timeout-minutes: 30
    runs-on: ubuntu-latest
    if: "! contains(toJSON(github.event.commits.*.message), '[skip ci]')"
    steps:
      - name: WIP Blocker
        uses: rafaelbeckel/wip-blocker@main
        
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup node
        uses: actions/setup-node@v2
        with:
          node-version: '16'

      - name: Extract current version
        id: get_version
        run: |
          CURRENT_VERSION=$(cat version | awk '{$1=$1;print}')
          echo "CURRENT_VERSION=${CURRENT_VERSION}" >> $GITHUB_ENV

      - name: Publish to NPM
        run: |
          LATEST_VERSION=$(npm show lerna-test-for-skypesky version)
          echo "CURRENT_VERSION is $CURRENT_VERSION, LATEST_VERSION is $LATEST_VERSION"
          # https://www.npmjs.com/package/compare-versions-cli
          npm install -g compare-versions-cli
          COMPARE=$(compare-versions-cli $CURRENT_VERSION $LATEST_VERSION)
          if [ $COMPARE -le 0 ] 
          then
              echo "CURRENT_VERSION($CURRENT_VERSION) must greater than LATEST_VERSION($LATEST_VERSION)"
              exit 1
          fi



     
